### ISSUE TITLE
Got rate limit error

### ISSUE THREAD

**Issue by arronKler** [honojs/create-hono#15] opened 2023-12-07 03:54 UTC
Got rate limit error from viaContentsApi call when execute `npm create hono`

![image](https://github.com/honojs/create-hono/assets/11434728/7d9c6ac7-51d4-47a4-b3f8-a6206d88e8d9)

**Comment by ryuapp** [comment] 2024-01-24 12:43
I think it would be better to include starter templates in this package.
For example, [create-vite](https://github.com/vitejs/vite/tree/main/packages/create-vite#readme).

That will resolve this issue and we can get old Hono templates.
The latter has no pros, it's just a historical legacy.

**Comment by JunQu** [comment] 2024-03-25 15:19
i have the same problem

**Comment by anhtuank7c** [comment] 2024-03-28 13:19
Unbelievable they keep this issue that long.

**Comment by yusukebe** [comment] 2024-03-28 13:43
@anhtuank7c 

We have our own priorities.

**Comment by yusukebe** [comment] 2024-03-28 13:43
@ryuapp

For this Issues, I don't want to include the template in `create-hono` as much as possible, can't we have it downloaded from GitHub without using the GitHub API?

**Comment by anhtuank7c** [comment] 2024-03-28 13:50
I think this is a gate for everyone to jump into `Hono` world but it just doesn't work. Its like you're selling thing that people want to buy it then you said: sorry, we don't have it.
@yusukebe sure, keep your own priorities. I will find alternative such as Elysia.

**Comment by yusukebe** [comment] 2024-03-28 13:56
@anhtuank7c 

I see what you mean, but this error only occurs in environments that are rate-limited by GitHub's API. So not everyone will face this problem.

**Comment by anhtuank7c** [comment] 2024-03-28 14:04
@yusukebe if you think it's a bug, it will be fixed one day. If you think it's not a bug, it will never be fixed because you never give a try at least once.

**Closed** 2024-03-28 14:14 UTC

**Comment by yusukebe** [comment] 2024-03-28 14:28
I solved this problem in a simple way that now it does not use GitHub API, so this error may not thrown with the latest version!

@ryuapp 

After all, I've hard coded the list of templates.

**Comment by anhtuank7c** [comment] 2024-03-28 14:48
🎉🎉🎉 @yusukebe Wow, what a beautiful fix.
